version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=your@password
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"  # Important: In a production environment your should remove the external port

  nosql.data:
    ports: 
    - "27017:27017"  # Important: In a production environment your should remove the external port

  redis.data:
    ports: 
    - "6379:6379"    # Important: In a production environment your should remove the external port
    
  rabbitmq:
    ports: 
    - "15672:15672"  # Important: In a production environment your should remove the external port
    - "5672:5672"    # Important: In a production environment your should remove the external port

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Initial Catalog=CatalogData;User Id=sa;Password=your@password
    expose: 
      - "80"
    ports:
      - "5101:80"  # Important: In a production environment your should remove the external port

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    ports:
      - "5100:80"  # Important: In a production environment your should remove the external port

