version: '3.4'

services:
  sql.data:
    environment:
      - SA_PASSWORD=your@password
      - ACCEPT_EULA=Y
    ports: 
      - "5433:1433"

  nosql.data:
    ports: 
    - "27017:27017"

  redis.data:
    ports: 
    - "6379:6379"
    
  rabbitmq:
    ports: 
    - "15672:15672" 
    - "5672:5672"

  catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionString=Server=sql.data;Initial Catalog=CatalogData;User Id=sa;Password=your@password   
    ports:
      - "80:80"

  webmvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"

